---
services:
  bind9:
    container_name: dns1
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=US/Denver
    volumes:
      - ./config/:/etc/bind:rw
    network_mode: host
    restart: unless-stopped
