# - hosts: all
- hosts: myhosts

  become: yes
  tasks:

  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: install core packages
    apt:
      name:
        - net-tools
        - tmux
        - nfs-common
        
      update_cache: yes