# - hosts: "{{ hosts }}"
- hosts: myhosts

  become: yes
  tasks:

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      remote_src: false #false=controller side, true=managed/remote side
      src: ./scripts/cloudflare_ddns/ddns.sh
      dest: /usr/local/bin/ddns.sh
      owner: root
      group: root
      mode: '0755'