# - hosts: "{{ hosts }}"
- hosts: linode

  become: yes
  tasks:

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      remote_src: yes
      src: /home/aearles/homelab/scripts/cloudflare_ddns/watchman_ddns.sh
      dest: /usr/local/bin/ddns.sh
      owner: root
      group: root
      mode: '0755'
