---
- name: Install Podman and Cockpit with Podman plugin on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages for Podman
      apt:
        name: 
          # - apt-transport-https
          # - ca-certificates
          - curl
          # - gnupg
          # - software-properties-common
          - podman
          - cockpit
          - cockpit-podman
