# - hosts: "{{ hosts }}"
- hosts: linode

  become: yes
  tasks:

  - name: Ensure a job that runs at 19 minutes, every 2 hours exists. Creates an entry like "19 */2 * * * sleep ${RANDOM:0:2}m ; /usr/local/bin/ddns.sh"
    ansible.builtin.cron:
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/cron_module.html
      name: "cloudflare_ddns"
      minute: "19"
      hour: "*/2"
      job: "sleep ${RANDOM:0:2}m ; /usr/local/bin/ddns.sh"