# https://github.com/TwiN/gatus?tab=readme-ov-file#table-of-contents
default-endpoint: &defaults
  interval: 60s
  client:
    insecure: true
    timeout: 30s
  conditions:
    - "[CONNECTED] == true"
  alerts:
    - type: ntfy

endpoints:

  - name: ICMP Example # https://github.com/TwiN/gatus?tab=readme-ov-file#monitoring-an-endpoint-using-icmp
    group: Main
    url: icmp://test01.example.internal
    conditions:
      - "[CONNECTED] == true"

  - name: HTTP Example
    group: Infrastructure
    <<: *defaults
    url: "http://test02.example.internal:81/"

  - name: Self
    group: Infrastructure
    <<: *defaults
    url: http://docker.example.internal:8080
