version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=US/Denver
       ports:
            - 5055:5055
       volumes:
            - /docker/jellyseerr/config:/app/config
       restart: unless-stopped